name: testing-flexcv

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.1'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python -m install_rpackages
    - name: Run tests
      run: |
        pip install -e .
        pytest