name: Publish packages to PyPI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build the source tarball and the wheel
    runs-on: ubuntu-latest
    environment: PyPI Release
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Create packages
      run: |
        python -m build
    - name: Archive packages
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist

  publish:
    name: Publish the source tarball and the wheel to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment: testing
    permissions:
      id-token: write

    steps:
    - name: Download packages
      uses: actions/download-artifact@v3

    - name: Upload packages
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
